remote_theme: pages-themes/cayman@v0.2.0

title: Guilherme Silva
description: Explorando matemática - abstrata e aplicada.

# Navegação do menu
header_pages:
  - pura.md
  - aplicada.md
  - reflexoes.md

# Informações adicionais
author: Guilherme Silva
email: guilsilva2005@gmail.com

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
