theme: minima
title: Guilherme Silva
description: Explorando matemática - abstrata e aplicada.

# Navegação do menu
header_pages:
  - pura.md
  - aplicada.md
  - reflexoes.md

# Informações adicionais
author: Guilherme Silva
email: guilsilva2005@gmail.com  # opcional

# Plugins (opcional)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

